#-----------------------------------------------------------------------------------------------#
# Effects List - All effect implementations                                                      #
#-----------------------------------------------------------------------------------------------#

SOURCES +=                                                                                      \
    ../OpenRGBEffectsPlugin/Effects/Ambient/Ambient.cpp                                         \
    ../OpenRGBEffectsPlugin/Effects/Ambient/RectangleSelector.cpp                               \
    ../OpenRGBEffectsPlugin/Effects/AudioBubbles/AudioBubbles.cpp                               \
    ../OpenRGBEffectsPlugin/Effects/AudioParty/AudioParty.cpp                                   \
    ../OpenRGBEffectsPlugin/Effects/AudioSine/AudioSine.cpp                                     \
    ../OpenRGBEffectsPlugin/Effects/AudioStar/AudioStar.cpp                                     \
    ../OpenRGBEffectsPlugin/Effects/AudioSync/AudioSync.cpp                                     \
    ../OpenRGBEffectsPlugin/Effects/AudioVisualizer/AudioVisualizer.cpp                         \
    ../OpenRGBEffectsPlugin/Effects/AudioVUMeter/AudioVUMeter.cpp                               \
    ../OpenRGBEffectsPlugin/Effects/Bloom/Bloom.cpp                                             \
    ../OpenRGBEffectsPlugin/Effects/BouncingBall/BouncingBall.cpp                               \
    ../OpenRGBEffectsPlugin/Effects/BouncingBall/BouncingBallSimulation.cpp                     \
    ../OpenRGBEffectsPlugin/Effects/Breathing/Breathing.cpp                                     \
    ../OpenRGBEffectsPlugin/Effects/BreathingCircle/BreathingCircle.cpp                         \
    ../OpenRGBEffectsPlugin/Effects/Bubbles/Bubbles.cpp                                         \
    ../OpenRGBEffectsPlugin/Effects/Clock/Clock.cpp                                             \
    ../OpenRGBEffectsPlugin/Effects/ColorWheel/ColorWheel.cpp                                   \
    ../OpenRGBEffectsPlugin/Effects/Comet/Comet.cpp                                             \
    ../OpenRGBEffectsPlugin/Effects/CrossingBeams/CrossingBeams.cpp                             \
    ../OpenRGBEffectsPlugin/Effects/CustomBlink/CustomBlink.cpp                                 \
    ../OpenRGBEffectsPlugin/Effects/CustomGradientWave/CustomGradientWave.cpp                   \
    ../OpenRGBEffectsPlugin/Effects/CustomMarquee/CustomMarquee.cpp                             \
    ../OpenRGBEffectsPlugin/Effects/DoubleRotatingRainbow/DoubleRotatingRainbow.cpp             \
    ../OpenRGBEffectsPlugin/Effects/Fill/Fill.cpp                                               \
    ../OpenRGBEffectsPlugin/Effects/FractalMotion/FractalMotion.cpp                             \
    ../OpenRGBEffectsPlugin/Effects/GifPlayer/GifPlayer.cpp                                     \
    ../OpenRGBEffectsPlugin/Effects/GradientWave/GradientWave.cpp                               \
    ../OpenRGBEffectsPlugin/Effects/Hypnotoad/Hypnotoad.cpp                                     \
    ../OpenRGBEffectsPlugin/Effects/Layers/Layers.cpp                                           \
    ../OpenRGBEffectsPlugin/Effects/Layers/LayerEntry.cpp                                       \
    ../OpenRGBEffectsPlugin/Effects/Layers/LayerGroupEntry.cpp                                  \
    ../OpenRGBEffectsPlugin/Effects/Lightning/Lightning.cpp                                     \
    ../OpenRGBEffectsPlugin/Effects/Marquee/Marquee.cpp                                         \
    ../OpenRGBEffectsPlugin/Effects/Mask/Mask.cpp                                               \
    ../OpenRGBEffectsPlugin/Effects/Mosaic/Mosaic.cpp                                           \
    ../OpenRGBEffectsPlugin/Effects/MotionPoint/MotionPoint.cpp                                 \
    ../OpenRGBEffectsPlugin/Effects/MotionPoints/MotionPoints.cpp                               \
    ../OpenRGBEffectsPlugin/Effects/MovingPanes/MovingPanes.cpp                                 \
    ../OpenRGBEffectsPlugin/Effects/Policing/Policing.cpp                                       \
    ../OpenRGBEffectsPlugin/Effects/RadialRainbow/RadialRainbow.cpp                             \
    ../OpenRGBEffectsPlugin/Effects/Rain/Rain.cpp                                               \
    ../OpenRGBEffectsPlugin/Effects/RainbowWave/RainbowWave.cpp                                 \
    ../OpenRGBEffectsPlugin/Effects/RandomMarquee/RandomMarquee.cpp                             \
    ../OpenRGBEffectsPlugin/Effects/RandomSpin/RandomSpin.cpp                                   \
    ../OpenRGBEffectsPlugin/Effects/RotatingBeam/RotatingBeam.cpp                               \
    ../OpenRGBEffectsPlugin/Effects/RotatingRainbow/RotatingRainbow.cpp                         \
    ../OpenRGBEffectsPlugin/Effects/Sequence/Sequence.cpp                                       \
    ../OpenRGBEffectsPlugin/Effects/SmoothBlink/SmoothBlink.cpp                                 \
    ../OpenRGBEffectsPlugin/Effects/SingleColor/SingleColor.cpp                                 \
    ../OpenRGBEffectsPlugin/Effects/SpectrumCycling/SpectrumCycling.cpp                         \
    ../OpenRGBEffectsPlugin/Effects/SparkleFade/SparkleFade.cpp                                 \
    ../OpenRGBEffectsPlugin/Effects/Spiral/Spiral.cpp                                           \
    ../OpenRGBEffectsPlugin/Effects/Stack/Stack.cpp                                             \
    ../OpenRGBEffectsPlugin/Effects/StarryNight/StarryNight.cpp                                 \
    ../OpenRGBEffectsPlugin/Effects/Sunrise/Sunrise.cpp                                         \
    ../OpenRGBEffectsPlugin/Effects/Swap/Swap.cpp                                               \
    ../OpenRGBEffectsPlugin/Effects/SwirlCircles/SwirlCircles.cpp                               \
    ../OpenRGBEffectsPlugin/Effects/SwirlCirclesAudio/SwirlCirclesAudio.cpp                     \
    ../OpenRGBEffectsPlugin/Effects/Visor/Visor.cpp                                             \
    ../OpenRGBEffectsPlugin/Effects/Wavy/Wavy.cpp                                               \
    ../OpenRGBEffectsPlugin/Effects/ZigZag/ZigZag.cpp                                           \

HEADERS +=                                                                                      \
    ../OpenRGBEffectsPlugin/Effects/Ambient/Ambient.h                                           \
    ../OpenRGBEffectsPlugin/Effects/Ambient/RectangleSelector.h                                 \
    ../OpenRGBEffectsPlugin/Effects/AudioBubbles/AudioBubbles.h                                 \
    ../OpenRGBEffectsPlugin/Effects/AudioParty/AudioParty.h                                     \
    ../OpenRGBEffectsPlugin/Effects/AudioSine/AudioSine.h                                       \
    ../OpenRGBEffectsPlugin/Effects/AudioStar/AudioStar.h                                       \
    ../OpenRGBEffectsPlugin/Effects/AudioSync/AudioSync.h                                       \
    ../OpenRGBEffectsPlugin/Effects/AudioVisualizer/AudioVisualizer.h                           \
    ../OpenRGBEffectsPlugin/Effects/AudioVUMeter/AudioVUMeter.h                                 \
    ../OpenRGBEffectsPlugin/Effects/Bloom/Bloom.h                                               \
    ../OpenRGBEffectsPlugin/Effects/BouncingBall/BouncingBall.h                                 \
    ../OpenRGBEffectsPlugin/Effects/BouncingBall/BouncingBallSimulation.h                       \
    ../OpenRGBEffectsPlugin/Effects/Breathing/Breathing.h                                       \
    ../OpenRGBEffectsPlugin/Effects/BreathingCircle/BreathingCircle.h                           \
    ../OpenRGBEffectsPlugin/Effects/Bubbles/Bubbles.h                                           \
    ../OpenRGBEffectsPlugin/Effects/Clock/Clock.h                                               \
    ../OpenRGBEffectsPlugin/Effects/ColorWheel/ColorWheel.h                                     \
    ../OpenRGBEffectsPlugin/Effects/Comet/Comet.h                                               \
    ../OpenRGBEffectsPlugin/Effects/CrossingBeams/CrossingBeams.h                               \
    ../OpenRGBEffectsPlugin/Effects/CustomBlink/CustomBlink.h                                   \
    ../OpenRGBEffectsPlugin/Effects/CustomGradientWave/CustomGradientWave.h                     \
    ../OpenRGBEffectsPlugin/Effects/CustomMarquee/CustomMarquee.h                               \
    ../OpenRGBEffectsPlugin/Effects/DoubleRotatingRainbow/DoubleRotatingRainbow.h               \
    ../OpenRGBEffectsPlugin/Effects/Fill/Fill.h                                                 \
    ../OpenRGBEffectsPlugin/Effects/FractalMotion/FractalMotion.h                               \
    ../OpenRGBEffectsPlugin/Effects/GifPlayer/GifPlayer.h                                       \
    ../OpenRGBEffectsPlugin/Effects/GradientWave/GradientWave.h                                 \
    ../OpenRGBEffectsPlugin/Effects/Hypnotoad/Hypnotoad.h                                       \
    ../OpenRGBEffectsPlugin/Effects/Layers/Layers.h                                             \
    ../OpenRGBEffectsPlugin/Effects/Layers/LayerEntry.h                                         \
    ../OpenRGBEffectsPlugin/Effects/Layers/LayerGroupEntry.h                                    \
    ../OpenRGBEffectsPlugin/Effects/Lightning/Lightning.h                                       \
    ../OpenRGBEffectsPlugin/Effects/Marquee/Marquee.h                                           \
    ../OpenRGBEffectsPlugin/Effects/Mask/Mask.h                                                 \
    ../OpenRGBEffectsPlugin/Effects/Mosaic/Mosaic.h                                             \
    ../OpenRGBEffectsPlugin/Effects/MotionPoint/MotionPoint.h                                   \
    ../OpenRGBEffectsPlugin/Effects/MotionPoints/MotionPoints.h                                 \
    ../OpenRGBEffectsPlugin/Effects/MovingPanes/MovingPanes.h                                   \
    ../OpenRGBEffectsPlugin/Effects/Policing/Policing.h                                         \
    ../OpenRGBEffectsPlugin/Effects/RadialRainbow/RadialRainbow.h                               \
    ../OpenRGBEffectsPlugin/Effects/Rain/Rain.h                                                 \
    ../OpenRGBEffectsPlugin/Effects/RainbowWave/RainbowWave.h                                   \
    ../OpenRGBEffectsPlugin/Effects/RandomMarquee/RandomMarquee.h                               \
    ../OpenRGBEffectsPlugin/Effects/RandomSpin/RandomSpin.h                                     \
    ../OpenRGBEffectsPlugin/Effects/RotatingBeam/RotatingBeam.h                                 \
    ../OpenRGBEffectsPlugin/Effects/RotatingRainbow/RotatingRainbow.h                           \
    ../OpenRGBEffectsPlugin/Effects/Sequence/Sequence.h                                         \
    ../OpenRGBEffectsPlugin/Effects/SmoothBlink/SmoothBlink.h                                   \
    ../OpenRGBEffectsPlugin/Effects/SingleColor/SingleColor.h                                   \
    ../OpenRGBEffectsPlugin/Effects/SparkleFade/SparkleFade.h                                   \
    ../OpenRGBEffectsPlugin/Effects/SpectrumCycling/SpectrumCycling.h                           \
    ../OpenRGBEffectsPlugin/Effects/Spiral/Spiral.h                                             \
    ../OpenRGBEffectsPlugin/Effects/Stack/Stack.h                                               \
    ../OpenRGBEffectsPlugin/Effects/StarryNight/StarryNight.h                                   \
    ../OpenRGBEffectsPlugin/Effects/Sunrise/Sunrise.h                                           \
    ../OpenRGBEffectsPlugin/Effects/Swap/Swap.h                                                 \
    ../OpenRGBEffectsPlugin/Effects/SwirlCircles/SwirlCircles.h                                 \
    ../OpenRGBEffectsPlugin/Effects/SwirlCirclesAudio/SwirlCirclesAudio.h                       \
    ../OpenRGBEffectsPlugin/Effects/Visor/Visor.h                                               \
    ../OpenRGBEffectsPlugin/Effects/Wavy/Wavy.h                                                 \
    ../OpenRGBEffectsPlugin/Effects/ZigZag/ZigZag.h                                             \

FORMS +=                                                                                        \
    ../OpenRGBEffectsPlugin/Effects/Ambient/Ambient.ui                                          \
    ../OpenRGBEffectsPlugin/Effects/AudioBubbles/AudioBubbles.ui                                \
    ../OpenRGBEffectsPlugin/Effects/AudioParty/AudioParty.ui                                    \
    ../OpenRGBEffectsPlugin/Effects/AudioSine/AudioSine.ui                                      \
    ../OpenRGBEffectsPlugin/Effects/AudioStar/AudioStar.ui                                      \
    ../OpenRGBEffectsPlugin/Effects/AudioSync/AudioSync.ui                                      \
    ../OpenRGBEffectsPlugin/Effects/AudioVisualizer/AudioVisualizer.ui                          \
    ../OpenRGBEffectsPlugin/Effects/AudioVUMeter/AudioVUMeter.ui                                \
    ../OpenRGBEffectsPlugin/Effects/Bloom/Bloom.ui                                              \
    ../OpenRGBEffectsPlugin/Effects/BouncingBall/BouncingBall.ui                                \
    ../OpenRGBEffectsPlugin/Effects/Breathing/Breathing.ui                                      \
    ../OpenRGBEffectsPlugin/Effects/BreathingCircle/BreathingCircle.ui                          \
    ../OpenRGBEffectsPlugin/Effects/Bubbles/Bubbles.ui                                          \
    ../OpenRGBEffectsPlugin/Effects/Clock/Clock.ui                                              \
    ../OpenRGBEffectsPlugin/Effects/ColorWheel/ColorWheel.ui                                    \
    ../OpenRGBEffectsPlugin/Effects/Comet/Comet.ui                                              \
    ../OpenRGBEffectsPlugin/Effects/CrossingBeams/CrossingBeams.ui                              \
    ../OpenRGBEffectsPlugin/Effects/CustomBlink/CustomBlink.ui                                  \
    ../OpenRGBEffectsPlugin/Effects/CustomGradientWave/CustomGradientWave.ui                    \
    ../OpenRGBEffectsPlugin/Effects/CustomMarquee/CustomMarquee.ui                              \
    ../OpenRGBEffectsPlugin/Effects/DoubleRotatingRainbow/DoubleRotatingRainbow.ui              \
    ../OpenRGBEffectsPlugin/Effects/Fill/Fill.ui                                                \
    ../OpenRGBEffectsPlugin/Effects/FractalMotion/FractalMotion.ui                              \
    ../OpenRGBEffectsPlugin/Effects/SingleColor/SingleColor.ui                                  \
    ../OpenRGBEffectsPlugin/Effects/GifPlayer/GifPlayer.ui                                      \
    ../OpenRGBEffectsPlugin/Effects/Hypnotoad/Hypnotoad.ui                                      \
    ../OpenRGBEffectsPlugin/Effects/Layers/Layers.ui                                            \
    ../OpenRGBEffectsPlugin/Effects/Layers/LayerEntry.ui                                        \
    ../OpenRGBEffectsPlugin/Effects/Layers/LayerGroupEntry.ui                                   \
    ../OpenRGBEffectsPlugin/Effects/Lightning/Lightning.ui                                      \
    ../OpenRGBEffectsPlugin/Effects/Marquee/Marquee.ui                                          \
    ../OpenRGBEffectsPlugin/Effects/Mask/Mask.ui                                                \
    ../OpenRGBEffectsPlugin/Effects/Mosaic/Mosaic.ui                                            \
    ../OpenRGBEffectsPlugin/Effects/MotionPoint/MotionPoint.ui                                  \
    ../OpenRGBEffectsPlugin/Effects/MotionPoints/MotionPoints.ui                                \
    ../OpenRGBEffectsPlugin/Effects/MovingPanes/MovingPanes.ui                                  \
    ../OpenRGBEffectsPlugin/Effects/RadialRainbow/RadialRainbow.ui                              \
    ../OpenRGBEffectsPlugin/Effects/Rain/Rain.ui                                                \
    ../OpenRGBEffectsPlugin/Effects/RandomMarquee/RandomMarquee.ui                              \
    ../OpenRGBEffectsPlugin/Effects/RandomSpin/RandomSpin.ui                                    \
    ../OpenRGBEffectsPlugin/Effects/RotatingBeam/RotatingBeam.ui                                \
    ../OpenRGBEffectsPlugin/Effects/RotatingRainbow/RotatingRainbow.ui                          \
    ../OpenRGBEffectsPlugin/Effects/Sequence/Sequence.ui                                        \
    ../OpenRGBEffectsPlugin/Effects/SmoothBlink/SmoothBlink.ui                                  \
    ../OpenRGBEffectsPlugin/Effects/SparkleFade/SparkleFade.ui                                  \
    ../OpenRGBEffectsPlugin/Effects/SpectrumCycling/SpectrumCycling.ui                          \
    ../OpenRGBEffectsPlugin/Effects/Spiral/Spiral.ui                                            \
    ../OpenRGBEffectsPlugin/Effects/Stack/Stack.ui                                              \
    ../OpenRGBEffectsPlugin/Effects/StarryNight/StarryNight.ui                                  \
    ../OpenRGBEffectsPlugin/Effects/Sunrise/Sunrise.ui                                          \
    ../OpenRGBEffectsPlugin/Effects/Swap/Swap.ui                                                \
    ../OpenRGBEffectsPlugin/Effects/SwirlCircles/SwirlCircles.ui                                \
    ../OpenRGBEffectsPlugin/Effects/SwirlCirclesAudio/SwirlCirclesAudio.ui                      \
    ../OpenRGBEffectsPlugin/Effects/Wavy/Wavy.ui                                                \
    ../OpenRGBEffectsPlugin/Effects/ZigZag/ZigZag.ui                                            \

